#!/usr/bin/env python
"""One-time dataset cleanup + manifest builder.

The raw dataset under data/ is a YOLO-detection export (image + optional
bounding boxes). We only need image-level classification labels, and the
class name is already encoded in every filename (`<class-slug>_<idx>.<ext>`),
so that's treated as the ground truth. Bounding boxes, when present, are
kept purely as an optional crop hint to reduce background clutter -- their
embedded class id is NOT trusted.

What this script does, all idempotently (safe to re-run):
  1. Scans data/images/{train,val,test} + data/labels/{train,val,test} via
     snake_classifier.data_prep.scan_dataset (shared with make_cv_folds.py).
  2. Derives the class from the filename and builds a canonical, contiguous
     class_id mapping (alphabetical), dropping the "evaluation" class that
     ships in the original config but has zero example images.
  3. Cross-checks each label file's embedded class id against the filename
     class and reports mismatches (trusts the filename).
  4. Expands multi-box label files into one manifest row per box, and falls
     back to a full-image (no-crop) row for the images with empty label
     files.
  5. Verifies every image actually opens (drops + reports corrupt files).
  6. Writes data/manifests/{train,val,test}.csv consumed by
     snake_classifier.dataset.SnakeDataset.
  7. Rewrites data/class_mapping.json, data/dataset_info.json and
     data/dataset.yaml so they reflect reality instead of the stale export.
"""

from __future__ import annotations

import csv
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from snake_classifier.data_prep import SPLITS, scan_dataset

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
LOW_DATA_THRESHOLD = 15  # classes below this many total images get flagged


def main() -> None:
    scanned = scan_dataset(DATA_DIR)
    canonical_names = scanned["class_names"]
    class_mapping = {name: idx for idx, name in enumerate(canonical_names)}

    # Bucket the flat row list back into train/val/test based on which
    # images/{split}/ directory each image_path came from.
    rows_by_split: dict[str, list[dict]] = {s: [] for s in SPLITS}
    for row in scanned["rows"]:
        split = Path(row["image_path"]).parts[1]  # "images/<split>/..."
        row["class_id"] = class_mapping[row["class_name"]]
        rows_by_split[split].append(row)

    manifests_dir = DATA_DIR / "manifests"
    manifests_dir.mkdir(exist_ok=True)
    fieldnames = [
        "image_path",
        "class_name",
        "class_id",
        "x_center",
        "y_center",
        "width",
        "height",
        "source",
        "license_code",
    ]
    for split in SPLITS:
        out_path = manifests_dir / f"{split}.csv"
        with out_path.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows_by_split[split])

    # Per-split, per-class image counts (unique images, not box-expanded rows)
    image_counts = {split: Counter() for split in SPLITS}
    for split in SPLITS:
        seen = set()
        for row in rows_by_split[split]:
            key = row["image_path"]
            if key in seen:
                continue
            seen.add(key)
            image_counts[split][row["class_name"]] += 1

    total_counts = Counter()
    for split in SPLITS:
        total_counts.update(image_counts[split])

    class_counts = {name: total_counts.get(name, 0) for name in canonical_names}
    low_data_classes = {
        name: n for name, n in class_counts.items() if n < LOW_DATA_THRESHOLD
    }

    mismatches = scanned["mismatches"]
    empty_label_count = scanned["empty_label_count"]
    multi_box_count = scanned["multi_box_count"]
    corrupt_images = scanned["corrupt_images"]

    dataset_info = {
        "num_classes": len(canonical_names),
        "class_mapping": class_mapping,
        "class_counts": class_counts,
        "total_images": sum(class_counts.values()),
        "splits": {split: sum(image_counts[split].values()) for split in SPLITS},
        "low_data_classes": low_data_classes,
        "notes": [
            "Regenerated by scripts/prepare_data.py.",
            "'evaluation' class removed: present in the original export's "
            "config but had zero example images.",
            f"{empty_label_count} images had no bounding box in the raw "
            "YOLO labels; they fall back to full-image (uncropped) samples.",
            f"{multi_box_count} images had more than one bounding box; each "
            "box became a separate manifest row (same image, different crop).",
            f"{len(mismatches)} label files had a bounding-box class id that "
            "disagreed with the class encoded in the filename -- the "
            "filename was trusted and the box kept only for its geometry. "
            "See prepare_report.json for the full list.",
        ],
    }
    (DATA_DIR / "dataset_info.json").write_text(json.dumps(dataset_info, indent=2) + "\n")
    (DATA_DIR / "class_mapping.json").write_text(json.dumps(class_mapping, indent=2) + "\n")

    dataset_yaml_lines = ["names:"]
    for name in canonical_names:
        dataset_yaml_lines.append(f"- {name}")
    dataset_yaml_lines += [
        f"nc: {len(canonical_names)}",
        "path: .",
        "train: images/train",
        "val: images/val",
        "test: images/test",
    ]
    (DATA_DIR / "dataset.yaml").write_text("\n".join(dataset_yaml_lines) + "\n")

    report = {
        "corrupt_images": corrupt_images,
        "label_class_mismatches": mismatches,
        "low_data_classes": low_data_classes,
    }
    (DATA_DIR / "prepare_report.json").write_text(json.dumps(report, indent=2) + "\n")

    print(f"Classes: {len(canonical_names)}")
    print(f"Manifest rows: { {s: len(rows_by_split[s]) for s in SPLITS} }")
    print(f"Unique images: { {s: sum(image_counts[s].values()) for s in SPLITS} }")
    print(f"Empty-label (full-image fallback) samples: {empty_label_count}")
    print(f"Multi-box images: {multi_box_count}")
    print(f"Corrupt images dropped: {len(corrupt_images)}")
    print(f"Label/filename class mismatches: {len(mismatches)} (see data/prepare_report.json)")
    if low_data_classes:
        print(f"Low-data classes (< {LOW_DATA_THRESHOLD} images): {low_data_classes}")


if __name__ == "__main__":
    main()
